-- Supabase 프로젝트의 SQL Editor 에서 이 파일 전체를 한 번 실행하세요.
-- (대시보드 왼쪽 메뉴 > SQL Editor > New query > 아래 내용 붙여넣기 > Run)

-- 1. 상품 테이블 생성
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price integer not null,
  original_price integer,
  stock boolean not null default true,
  condition text,
  description text,
  image_url text,
  images jsonb not null default '[]'::jsonb,
  description_images jsonb not null default '[]'::jsonb,
  specs jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

-- 이미 products 테이블을 만든 적이 있다면 (컬럼이 없다면) 아래 세 줄만 추가로 실행하세요.
alter table public.products add column if not exists specs jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists images jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists description_images jsonb not null default '[]'::jsonb;

-- (선택) 기존에 image_url 에만 사진이 들어있던 상품들을 새 images 배열로 옮기고 싶다면 실행하세요.
-- (실행 안 해도 화면에는 자동으로 image_url 이 대신 보이니 필수는 아닙니다.)
update public.products
set images = jsonb_build_array(image_url)
where (images is null or images = '[]'::jsonb)
  and image_url is not null and image_url <> '';

-- 2. 기본 테이블 접근 권한 부여 (RLS 정책과는 별개로 반드시 필요합니다)
--    이게 없으면 정책을 다 맞게 설정해도 "permission denied for table products" 오류가 납니다.
grant usage on schema public to anon, authenticated;
grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;

-- 3. RLS(행 단위 보안) 활성화
alter table public.products enable row level security;

-- 4. 누구나 상품을 "조회"는 할 수 있게 허용 (홈페이지 방문자용)
create policy "Public can view products"
  on public.products for select
  using (true);

-- 5. 로그인한 관리자만 등록/수정/삭제 가능
create policy "Authenticated users can insert products"
  on public.products for insert
  with check (auth.role() = 'authenticated');

create policy "Authenticated users can update products"
  on public.products for update
  using (auth.role() = 'authenticated');

create policy "Authenticated users can delete products"
  on public.products for delete
  using (auth.role() = 'authenticated');

-- 6. 상품 사진을 저장할 스토리지 버킷 생성 (공개 읽기 가능)
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- 7. 스토리지 정책: 누구나 사진 조회 가능, 로그인한 관리자만 업로드/수정/삭제 가능
create policy "Public can view product images"
  on storage.objects for select
  using (bucket_id = 'product-images');

create policy "Authenticated users can upload product images"
  on storage.objects for insert
  with check (bucket_id = 'product-images' and auth.role() = 'authenticated');

create policy "Authenticated users can update product images"
  on storage.objects for update
  using (bucket_id = 'product-images' and auth.role() = 'authenticated');

create policy "Authenticated users can delete product images"
  on storage.objects for delete
  using (bucket_id = 'product-images' and auth.role() = 'authenticated');
